### ISSUE TITLE
Couldn't connect to server: Invalid IP

### ISSUE THREAD

**Issue by chamkank** [matheus23/RuinsOfRevenge#1]
Any help for the following error?
![image](https://cloud.githubusercontent.com/assets/12876696/14759168/1a5ad2c8-08cd-11e6-8eba-34d076b554b6.png)

This occurs when I try to connect to localhost. Is it likely to be a firewall issue, or do I have to setup a server specifically?

**Comment by sylvia43** [comment]
Are you running a server locally? It looks like it's expecting you to

**Comment by chamkank** [comment]
Nope, how would I go about doing that?

**Comment by sylvia43** [comment]
Depends, how are you building the project? You need to specify [this file](https://github.com/matheus23/RuinsOfRevenge/blob/master/src/org/matheusdev/ror/server/ServerMaster.java) as the entry point, which can be done manually with the two manifest files.

**Comment by chamkank** [comment]
Here are the contents of my manifest files. They seem to be correct as far as I can tell.

Server:

```
Manifest-Version: 1.0
Main-Class: org.matheusdev.ror.server.ServerMaster
```

Client:

```
Manifest-Version: 1.0
Main-Class: org.matheusdev.ror.RuinsOfRevenge
```

**Comment by sylvia43** [comment]
Okay so if you run the server and then the client what happens?

**Comment by chamkank** [comment]
Nevermind, I got it working. Turns out I had to run the server manually, thanks for the help!
